name: Terraform Infrastructure Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  AWS_REGION: ap-south-1

#############################
# PLAN STAGE
#############################

jobs:

  terraform-vpc-plan:
    name: VPC - Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: VPC

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init
      - run: terraform validate
      - run: terraform plan


  terraform-rds-plan:
    name: RDS - Plan
    needs: terraform-vpc-plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: RDS

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init
      - run: terraform validate
      - run: terraform plan


  terraform-compute-plan:
    name: compute - Plan
    needs: terraform-rds-plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: COMPUTE

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init
      - run: terraform validate
      - run: terraform plan


  terraform-alb-plan:
    name: ALB - Plan
    needs: terraform-compute-plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ALB

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init
      - run: terraform validate
      - run: terraform plan

#############################
# APPLY STAGE
#############################

  terraform-vpc-apply:
    name: VPC - Apply
    needs: terraform-alb-plan
    runs-on: ubuntu-latest

    environment:
      name: production

    defaults:
      run:
        working-directory: VPC

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init
      - run: terraform apply -auto-approve


  terraform-rds-apply:
    name: RDS - Apply
    needs: terraform-vpc-apply
    runs-on: ubuntu-latest

    environment:
      name: production

    defaults:
      run:
        working-directory: RDS

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init
      - run: terraform apply -auto-approve


  terraform-compute-apply:
    name: Compute - Apply
    needs: terraform-rds-apply
    runs-on: ubuntu-latest

    environment:
      name: production

    defaults:
      run:
        working-directory: COMPUTE

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init
      - run: terraform apply -auto-approve


  terraform-alb-apply:
    name: ALB - Apply
    needs: terraform-compute-apply
    runs-on: ubuntu-latest

    environment:
      name: production

    defaults:
      run:
        working-directory: ALB

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init
      - run: terraform apply -auto-approve